<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

        <title>Dawn Ferguson's HCDE 598 Digital Fabrications Page</title> 

        <link href="style.css" media="screen" rel="stylesheet" type="text/css" />

    </head> 
    <body> 
    
        <div class="header">
            <h1>Dawn Ferguson's Assignment 4: Moving Parts</h1>
            <p>
		    <img src="gears_final.jpg"width=400></a>
         <h2>Steps Taken:</h2>
             <p>
		I wanted to work with gears for this assignment and had really high hopes to make a rotating bear with a rastered tutu and facial expressions, however my time and skills demanded a more simplified approach.
                </p>
	     <img src="base_final.jpg" width=250></a>
	<p>
		I built the base in onshape and thought about using a carriage bolt to attach the gears to the base, but found that was overcomplicated when a simle extruded cylinder would work well. The base has a thickness of 3mm.I built the rectangle forst, extruded the shape and then built a second rectangle that I use to take out the interior.
	</p>
                <p>
		I then created two smaller circles on top and extruded them from the surface. At first the small cylinders on topwere hollow, but I played around with the tool until I got them to be solid.Then I used the dimensioning tool to set their distance apart to align with the distance from my gears origin. 
		</p>
			 <img src="onshape_gear_inst.jpg" width=250></a>
		<p>
			I used the featurescript gear generator in Onshape and heavily edited the gears to get what I wanted. They start with sebveral gears. I deleted out the ones I didn't want and started to edit the ones I wanted to keep. 
		<p>	
			Once I had two gears left I started editing their thickness and size. This caused them to overlap and merge. I then needed to locate the area of the sketch where I could change the distance between the gears by using half the sum of the calculated pitch circle diameter for each gear.
		 <p>
			<a href="HCDE598cut5.ai"> This is my stl files</a>
        </div>
        
    </body>
</html>
